package com.sansim.app.util

import android.content.Context
import android.graphics.BitmapFactory
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.platform.LocalContext

object CardBackgroundLoader {
    // 区号到背景图片文件名的映射
    private val dialCodeToFile = mapOf(
        "+93" to "card-background-afghanistan-lighttrail.jpg",
        "+355" to "card-background-albania-lighttrail.jpg",
        "+213" to "card-background-algeria-lighttrail.jpg",
        "+376" to "card-background-andorra-lighttrail.jpg",
        "+244" to "card-background-angola-lighttrail.jpg",
        "+1" to "card-background-united-states-lighttrail.jpg",
        "+54" to "card-background-argentina-lighttrail.jpg",
        "+374" to "card-background-armenia-lighttrail.jpg",
        "+61" to "card-background-australia-lighttrail.jpg",
        "+43" to "card-background-austria-lighttrail.jpg",
        "+994" to "card-background-azerbaijan-lighttrail.jpg",
        "+1" to "card-background-united-states-lighttrail.jpg",
        "+973" to "card-background-bahrain-lighttrail.jpg",
        "+880" to "card-background-bangladesh-lighttrail.jpg",
        "+1" to "card-background-united-states-lighttrail.jpg",
        "+375" to "card-background-belarus-lighttrail.jpg",
        "+32" to "card-background-belgium-lighttrail.png",
        "+501" to "card-background-belize-lighttrail.png",
        "+229" to "card-background-benin-lighttrail.jpg",
        "+975" to "card-background-bhutan-lighttrail.jpg",
        "+591" to "card-background-bolivia-lighttrail.jpg",
        "+387" to "card-background-bosnia-herzegovina-lighttrail.jpg",
        "+267" to "card-background-botswana-lighttrail.jpg",
        "+55" to "card-background-brazil-lighttrail.jpg",
        "+673" to "card-background-brunei-lighttrail.png",
        "+359" to "card-background-bulgaria-lighttrail.png",
        "+226" to "card-background-burkina-faso-lighttrail.png",
        "+257" to "card-background-burundi-lighttrail.png",
        "+238" to "card-background-cape-verde-lighttrail.jpg",
        "+855" to "card-background-cambodia-lighttrail.png",
        "+237" to "card-background-cameroon-lighttrail.png",
        "+1" to "card-background-canada-lighttrail.png",
        "+236" to "card-background-central-african-republic-lighttrail.jpg",
        "+235" to "card-background-chad-lighttrail.jpg",
        "+56" to "card-background-chile-lighttrail.jpg",
        "+86" to "card-background-china-lighttrail.jpg",
        "+57" to "card-background-colombia-lighttrail.jpg",
        "+269" to "card-background-comoros-lighttrail.jpg",
        "+242" to "card-background-congo-brazzaville-lighttrail.jpg",
        "+243" to "card-background-congo-kinshasa-lighttrail.jpg",
        "+506" to "card-background-costa-rica-lighttrail.jpg",
        "+225" to "card-background-cote-divoire-lighttrail.jpg",
        "+385" to "card-background-croatia-lighttrail.jpg",
        "+53" to "card-background-cuba-lighttrail.jpg",
        "+357" to "card-background-cyprus-lighttrail.jpg",
        "+420" to "card-background-czechia-lighttrail.jpg",
        "+45" to "card-background-denmark-lighttrail.jpg",
        "+253" to "card-background-djibouti-lighttrail.jpg",
        "+1" to "card-background-united-states-lighttrail.jpg",
        "+1" to "card-background-united-states-lighttrail.jpg",
        "+593" to "card-background-ecuador-lighttrail.jpg",
        "+20" to "card-background-egypt-lighttrail.jpg",
        "+503" to "card-background-el-salvador-lighttrail.jpg",
        "+240" to "card-background-equatorial-guinea-lighttrail.jpg",
        "+291" to "card-background-eritrea-lighttrail.jpg",
        "+372" to "card-background-estonia-lighttrail.jpg",
        "+268" to "card-background-eswatini-lighttrail.jpg",
        "+251" to "card-background-ethiopia-lighttrail.jpg",
        "+679" to "card-background-fiji-lighttrail.jpg",
        "+358" to "card-background-finland-lighttrail.jpg",
        "+33" to "card-background-france-lighttrail.jpg",
        "+241" to "card-background-gabon-lighttrail.jpg",
        "+220" to "card-background-gambia-lighttrail.jpg",
        "+995" to "card-background-georgia-lighttrail.jpg",
        "+49" to "card-background-germany-lighttrail.jpg",
        "+233" to "card-background-ghana-lighttrail.jpg",
        "+30" to "card-background-greece-lighttrail.jpg",
        "+1" to "card-background-united-states-lighttrail.jpg",
        "+502" to "card-background-guatemala-lighttrail.jpg",
        "+224" to "card-background-guinea-lighttrail.jpg",
        "+245" to "card-background-guinea-bissau-lighttrail.jpg",
        "+592" to "card-background-guyana-lighttrail.jpg",
        "+509" to "card-background-haiti-lighttrail.jpg",
        "+504" to "card-background-honduras-lighttrail.jpg",
        "+852" to "card-background-hong-kong-lighttrail.jpg",
        "+36" to "card-background-hungary-lighttrail.jpg",
        "+354" to "card-background-iceland-lighttrail.jpg",
        "+91" to "card-background-india-lighttrail.jpg",
        "+62" to "card-background-indonesia-lighttrail.jpg",
        "+98" to "card-background-iran-lighttrail.jpg",
        "+964" to "card-background-iraq-lighttrail.jpg",
        "+353" to "card-background-ireland-lighttrail.jpg",
        "+972" to "card-background-israel-lighttrail.jpg",
        "+39" to "card-background-italy-lighttrail.jpg",
        "+1" to "card-background-united-states-lighttrail.jpg",
        "+81" to "card-background-japan-lighttrail.jpg",
        "+962" to "card-background-jordan-lighttrail.jpg",
        "+7" to "card-background-kazakhstan-lighttrail.jpg",
        "+254" to "card-background-kenya-lighttrail.jpg",
        "+686" to "card-background-kiribati-lighttrail.jpg",
        "+82" to "card-background-south-korea-lighttrail.jpg",
        "+965" to "card-background-kuwait-lighttrail.jpg",
        "+996" to "card-background-kyrgyzstan-lighttrail.jpg",
        "+856" to "card-background-laos-lighttrail.jpg",
        "+371" to "card-background-latvia-lighttrail.jpg",
        "+961" to "card-background-lebanon-lighttrail.jpg",
        "+266" to "card-background-lesotho-lighttrail.jpg",
        "+231" to "card-background-liberia-lighttrail.jpg",
        "+218" to "card-background-libya-lighttrail.jpg",
        "+423" to "card-background-liechtenstein-lighttrail.jpg",
        "+370" to "card-background-lithuania-lighttrail.jpg",
        "+352" to "card-background-luxembourg-lighttrail.jpg",
        "+853" to "card-background-macau-lighttrail.jpg",
        "+261" to "card-background-madagascar-lighttrail.jpg",
        "+265" to "card-background-malawi-lighttrail.jpg",
        "+60" to "card-background-malaysia-lighttrail.jpg",
        "+960" to "card-background-maldives-lighttrail.jpg",
        "+223" to "card-background-mali-lighttrail.jpg",
        "+356" to "card-background-malta-lighttrail.jpg",
        "+692" to "card-background-marshall-islands-lighttrail.jpg",
        "+222" to "card-background-mauritania-lighttrail.jpg",
        "+230" to "card-background-mauritius-lighttrail.jpg",
        "+52" to "card-background-mexico-lighttrail.jpg",
        "+691" to "card-background-micronesia-lighttrail.jpg",
        "+373" to "card-background-moldova-lighttrail.jpg",
        "+377" to "card-background-monaco-lighttrail.jpg",
        "+976" to "card-background-mongolia-lighttrail.jpg",
        "+382" to "card-background-montenegro-lighttrail.jpg",
        "+212" to "card-background-morocco-lighttrail.jpg",
        "+258" to "card-background-mozambique-lighttrail.jpg",
        "+95" to "card-background-myanmar-lighttrail.jpg",
        "+264" to "card-background-namibia-lighttrail.jpg",
        "+31" to "card-background-netherlands-lighttrail.jpg",
        "+64" to "card-background-new-zealand-lighttrail.jpg",
        "+505" to "card-background-nicaragua-lighttrail.jpg",
        "+227" to "card-background-niger-lighttrail.jpg",
        "+234" to "card-background-nigeria-lighttrail.jpg",
        "+47" to "card-background-norway-lighttrail.jpg",
        "+968" to "card-background-oman-lighttrail.jpg",
        "+92" to "card-background-pakistan-lighttrail.jpg",
        "+507" to "card-background-panama-lighttrail.jpg",
        "+675" to "card-background-papua-new-guinea-lighttrail.jpg",
        "+595" to "card-background-paraguay-lighttrail.jpg",
        "+51" to "card-background-peru-lighttrail.jpg",
        "+63" to "card-background-philippines-lighttrail.jpg",
        "+48" to "card-background-poland-lighttrail.jpg",
        "+351" to "card-background-portugal-lighttrail.jpg",
        "+974" to "card-background-qatar-lighttrail.jpg",
        "+40" to "card-background-romania-lighttrail.jpg",
        "+7" to "card-background-russia-lighttrail.jpg",
        "+250" to "card-background-rwanda-lighttrail.jpg",
        "+966" to "card-background-saudi-arabia-lighttrail.jpg",
        "+221" to "card-background-senegal-lighttrail.jpg",
        "+381" to "card-background-serbia-lighttrail.jpg",
        "+65" to "card-background-singapore-lighttrail.jpg",
        "+421" to "card-background-slovakia-lighttrail.jpg",
        "+386" to "card-background-slovenia-lighttrail.jpg",
        "+252" to "card-background-somalia-lighttrail.jpg",
        "+27" to "card-background-south-africa-lighttrail.jpg",
        "+82" to "card-background-south-korea-lighttrail.jpg",
        "+34" to "card-background-spain-lighttrail.jpg",
        "+94" to "card-background-sri-lanka-lighttrail.jpg",
        "+249" to "card-background-sudan-lighttrail.jpg",
        "+597" to "card-background-suriname-lighttrail.jpg",
        "+46" to "card-background-sweden-lighttrail.jpg",
        "+41" to "card-background-switzerland-lighttrail.jpg",
        "+963" to "card-background-syria-lighttrail.jpg",
        "+886" to "card-background-taiwan-lighttrail.jpg",
        "+992" to "card-background-tajikistan-lighttrail.jpg",
        "+255" to "card-background-tanzania-lighttrail.jpg",
        "+66" to "card-background-thailand-lighttrail.jpg",
        "+670" to "card-background-timor-leste-lighttrail.jpg",
        "+228" to "card-background-togo-lighttrail.jpg",
        "+676" to "card-background-tonga-lighttrail.jpg",
        "+1" to "card-background-united-states-lighttrail.jpg",
        "+216" to "card-background-tunisia-lighttrail.jpg",
        "+90" to "card-background-turkey-lighttrail.jpg",
        "+993" to "card-background-turkmenistan-lighttrail.jpg",
        "+688" to "card-background-tuvalu-lighttrail.jpg",
        "+256" to "card-background-uganda-lighttrail.jpg",
        "+380" to "card-background-ukraine-lighttrail.jpg",
        "+971" to "card-background-united-arab-emirates-lighttrail.jpg",
        "+44" to "card-background-united-kingdom-lighttrail.jpg",
        "+1" to "card-background-united-states-lighttrail.jpg",
        "+598" to "card-background-uruguay-lighttrail.jpg",
        "+998" to "card-background-uzbekistan-lighttrail.jpg",
        "+678" to "card-background-vanuatu-lighttrail.jpg",
        "+58" to "card-background-venezuela-lighttrail.jpg",
        "+84" to "card-background-vietnam-lighttrail.jpg",
        "+967" to "card-background-yemen-lighttrail.jpg",
        "+260" to "card-background-zambia-lighttrail.jpg",
        "+263" to "card-background-zimbabwe-lighttrail.jpg"
    )
    
    fun getCardBackgroundFileName(dialCode: String): String? {
        return dialCodeToFile[dialCode]
    }
    
    fun loadCardBackground(context: Context, dialCode: String): ImageBitmap? {
        val fileName = getCardBackgroundFileName(dialCode) ?: return null
        return try {
            val inputStream = context.assets.open("card_backgrounds/$fileName")
            val bitmap = BitmapFactory.decodeStream(inputStream)
            inputStream.close()
            bitmap?.asImageBitmap()
        } catch (e: Exception) {
            null
        }
    }
}

@Composable
fun rememberCardBackground(dialCode: String): ImageBitmap? {
    val context = LocalContext.current
    return remember(dialCode) {
        CardBackgroundLoader.loadCardBackground(context, dialCode)
    }
}
