package com.sansim.app.i18n

import android.content.Context
import com.sansim.app.data.model.OperatorDatabase

fun tr(lang:String, key:String):String {
    val extra = mapOf(
        "繁体中文" to mapOf(
            "云端提醒" to "雲端提醒", "启用云端提醒" to "啟用雲端提醒", "自动同步" to "自動同步", "自动同步说明" to "開啟後，新增/編輯/刪除/保號/匯入號碼和修改提醒設定時，會自動同步到雲端。", "API Key说明" to "每台手機生成一次固定 API Key；可直接貼上整段內容，App 會自動擷取真正的 Key 並去掉換行。", "当前 API Key：" to "目前 API Key：", "未设置" to "未設定", "连接成功" to "連線成功", "测试连接" to "測試連線", "已复制 API Key" to "已複製 API Key", "请先生成或填写 API Key" to "請先生成或填寫 API Key", "复制 Key" to "複製 Key", "已有固定Key说明" to "本機已有固定 Key，不會重複生成。如需換號請先手動清空 API Key。", "已生成本机固定 Key，已保存" to "已生成本機固定 Key，已儲存", "生成我的 Key" to "生成我的 Key", "同步成功" to "同步成功", "同步到云端" to "同步到雲端", "云端 Telegram" to "雲端 Telegram", "启用 TG 配置" to "啟用 TG 設定", "TG配置说明" to "先給機器人傳送 /start，再點測試TG。", "云端邮件" to "雲端郵件", "SMTP 自动发邮件" to "SMTP 自動發郵件", "SMTP 服务器" to "SMTP 伺服器", "端口" to "連接埠", "邮箱账号" to "郵箱帳號", "授权码" to "授權碼", "发件邮箱" to "寄件郵箱", "收件邮箱" to "收件郵箱", "SMTP授权码说明" to "授權碼不是郵箱登入密碼；QQ/網易/Gmail 都需要在郵箱後台生成 SMTP 授權碼。", "本地通知提醒" to "本地通知提醒", "通知一键发邮件" to "通知一鍵發郵件", "本地通知说明" to "本地通知依賴手機背景執行；雲端提醒由伺服器傳送，不怕手機被殺背景。", "TG 测试已发送" to "TG 測試已傳送", "测试TG" to "測試TG", "邮件测试已发送" to "郵件測試已傳送", "测试邮件" to "測試郵件", "已触发云端检查" to "已觸發雲端檢查", "立即检查到期" to "立即檢查到期", "云端服务说明" to "雲端服務會每 30 分鐘檢查一次。手機被殺背景時，伺服器仍可按已同步資料傳送 Telegram / 郵件提醒。每個人用獨立 API Key，資料互相隔離。", "真实下载数据测试" to "真實下載資料測試"),
        "English" to mapOf(
            "云端提醒" to "Cloud reminders", "启用云端提醒" to "Enable cloud reminders", "自动同步" to "Auto sync", "自动同步说明" to "When enabled, adding/editing/deleting/renewing/importing numbers and changing reminder settings will sync to the cloud automatically.", "API Key说明" to "Each phone generates one fixed API Key. You can paste a full message; the app extracts the real Key and removes line breaks.", "当前 API Key：" to "Current API Key: ", "未设置" to "Not set", "连接成功" to "Connected", "测试连接" to "Test connection", "已复制 API Key" to "API Key copied", "请先生成或填写 API Key" to "Generate or enter an API Key first", "复制 Key" to "Copy Key", "已有固定Key说明" to "This phone already has a fixed Key. To replace it, clear the API Key manually first.", "已生成本机固定 Key，已保存" to "Fixed Key generated and saved", "生成我的 Key" to "Generate my Key", "同步成功" to "Synced", "同步到云端" to "Sync to cloud", "云端 Telegram" to "Cloud Telegram", "启用 TG 配置" to "Enable TG config", "TG配置说明" to "Send /start to the bot first, then tap Test TG.", "云端邮件" to "Cloud email", "SMTP 自动发邮件" to "SMTP auto email", "SMTP 服务器" to "SMTP server", "端口" to "Port", "邮箱账号" to "Email account", "授权码" to "App password", "发件邮箱" to "From email", "收件邮箱" to "To email", "SMTP授权码说明" to "The app password is not your email login password. QQ/NetEase/Gmail require SMTP app passwords.", "本地通知提醒" to "Local notification", "通知一键发邮件" to "Email action in notification", "本地通知说明" to "Local notifications depend on phone background permissions. Cloud reminders are sent by the server.", "TG 测试已发送" to "TG test sent", "测试TG" to "Test TG", "邮件测试已发送" to "Email test sent", "测试邮件" to "Test email", "已触发云端检查" to "Cloud check triggered", "立即检查到期" to "Check expiry now", "云端服务说明" to "The cloud service checks every 30 minutes. Even if the phone app is killed, the server can still send Telegram/email reminders based on synced data. Each user has an isolated API Key.", "真实下载数据测试" to "Real download data test"),
        "日本語" to mapOf(
            "云端提醒" to "クラウド通知", "启用云端提醒" to "クラウド通知を有効化", "自动同步" to "自動同期", "自动同步说明" to "有効にすると、番号の追加・編集・削除・維持・インポートや通知設定の変更時に自動でクラウド同期します。", "API Key说明" to "端末ごとに固定 API Key を1回生成します。文章ごと貼り付けても Key を抽出し改行を削除します。", "当前 API Key：" to "現在の API Key：", "未设置" to "未設定", "连接成功" to "接続成功", "测试连接" to "接続テスト", "已复制 API Key" to "API Keyをコピーしました", "请先生成或填写 API Key" to "先に API Key を生成または入力してください", "复制 Key" to "Keyをコピー", "已有固定Key说明" to "この端末には固定 Key があります。変更する場合は先に API Key を手動で空にしてください。", "已生成本机固定 Key，已保存" to "端末固定 Key を生成して保存しました", "生成我的 Key" to "Keyを生成", "同步成功" to "同期成功", "同步到云端" to "クラウド同期", "云端 Telegram" to "クラウド Telegram", "启用 TG 配置" to "TG設定を有効化", "TG配置说明" to "先にBotへ /start を送ってからTGテストを押してください。", "云端邮件" to "クラウドメール", "SMTP 自动发邮件" to "SMTP自動メール", "SMTP 服务器" to "SMTPサーバー", "端口" to "ポート", "邮箱账号" to "メールアカウント", "授权码" to "アプリパスワード", "发件邮箱" to "送信元メール", "收件邮箱" to "宛先メール", "SMTP授权码说明" to "通常のログインパスワードではありません。QQ/NetEase/GmailではSMTP用アプリパスワードが必要です。", "本地通知提醒" to "ローカル通知", "通知一键发邮件" to "通知からメール送信", "本地通知说明" to "ローカル通知は端末のバックグラウンド権限に依存します。クラウド通知はサーバーから送信されます。", "TG 测试已发送" to "TGテスト送信済み", "测试TG" to "TGテスト", "邮件测试已发送" to "メールテスト送信済み", "测试邮件" to "メールテスト", "已触发云端检查" to "クラウドチェックを開始しました", "立即检查到期" to "今すぐ期限確認", "云端服务说明" to "クラウドサービスは30分ごとに確認します。アプリが終了されても、同期済みデータに基づきTelegram/メール通知を送信できます。各ユーザーは独立したAPI Keyで隔離されます。", "真实下载数据测试" to "実ダウンロードデータテスト"),
        "阿拉伯语" to mapOf(
            "云端提醒" to "تذكيرات السحابة", "启用云端提醒" to "تفعيل تذكيرات السحابة", "自动同步" to "مزامنة تلقائية", "自动同步说明" to "عند التفعيل، ستتم مزامنة الإضافة والتعديل والحذف والتجديد والاستيراد وتغييرات التذكير تلقائيًا.", "API Key说明" to "يتم إنشاء API Key ثابت لكل هاتف مرة واحدة. يمكن لصق النص كاملًا وسيستخرج التطبيق المفتاح الحقيقي.", "当前 API Key：" to "API Key الحالي: ", "未设置" to "غير مضبوط", "连接成功" to "تم الاتصال", "测试连接" to "اختبار الاتصال", "已复制 API Key" to "تم نسخ API Key", "请先生成或填写 API Key" to "أنشئ أو أدخل API Key أولاً", "复制 Key" to "نسخ Key", "已有固定Key说明" to "هذا الهاتف لديه Key ثابت بالفعل. لتغييره امسح API Key يدويًا أولاً.", "已生成本机固定 Key，已保存" to "تم إنشاء وحفظ Key ثابت", "生成我的 Key" to "إنشاء Key", "同步成功" to "تمت المزامنة", "同步到云端" to "مزامنة للسحابة", "云端 Telegram" to "Telegram السحابي", "启用 TG 配置" to "تفعيل إعداد TG", "TG配置说明" to "أرسل /start إلى البوت أولاً، ثم اختبر TG.", "云端邮件" to "البريد السحابي", "SMTP 自动发邮件" to "إرسال SMTP تلقائي", "SMTP 服务器" to "خادم SMTP", "端口" to "المنفذ", "邮箱账号" to "حساب البريد", "授权码" to "كلمة مرور التطبيق", "发件邮箱" to "بريد المرسل", "收件邮箱" to "بريد المستلم", "SMTP授权码说明" to "كلمة مرور التطبيق ليست كلمة مرور البريد. يتطلب QQ/NetEase/Gmail كلمة مرور SMTP خاصة.", "本地通知提醒" to "إشعار محلي", "通知一键发邮件" to "إرسال بريد من الإشعار", "本地通知说明" to "الإشعارات المحلية تعتمد على صلاحيات الخلفية. تذكيرات السحابة يرسلها الخادم.", "TG 测试已发送" to "تم إرسال اختبار TG", "测试TG" to "اختبار TG", "邮件测试已发送" to "تم إرسال اختبار البريد", "测试邮件" to "اختبار البريد", "已触发云端检查" to "تم تشغيل فحص السحابة", "立即检查到期" to "فحص الانتهاء الآن", "云端服务说明" to "تفحص خدمة السحابة كل 30 دقيقة. حتى إذا أُغلق التطبيق، يمكن للخادم إرسال تذكيرات Telegram/البريد حسب البيانات المتزامنة. لكل مستخدم API Key مستقل.", "真实下载数据测试" to "اختبار تنزيل بيانات حقيقي")
    )
    extra[lang]?.get(key)?.let { return it }

    val supplement = mapOf(
        "繁体中文" to mapOf(
            "流量接口" to "流量接口", "流量接口 URL" to "流量接口 URL", "默认流量 KB" to "預設流量 KB",
            "下载测试接口" to "下載測試接口", "目标流量" to "目標流量", "例：100KB / 1MB / 50MB" to "例：100KB / 1MB / 50MB",
            "204 / 空响应接口不能真正消耗流量，建议使用 Cloudflare 或 Hetzner。" to "204 / 空回應接口不能真正消耗流量，建議使用 Cloudflare 或 Hetzner。",
            "开始刷流量" to "開始刷流量", "确认刷流量？" to "確認刷流量？", "将实际下载约" to "將實際下載約", "确认后会真实消耗当前网络流量。" to "確認後會真實消耗目前網路流量。",
            "请求中…" to "請求中…", "成功" to "成功", "实际读取" to "實際讀取", "目标" to "目標", "耗时" to "耗時", "秒" to "秒", "约" to "約", "失败" to "失敗",
            "选择刷流量号码" to "選擇刷流量號碼", "选择拨号号码" to "選擇撥號號碼", "暂无号码，请先添加号码。" to "暫無號碼，請先新增號碼。",
            "支持 JSON / CSV，导入前建议先导出备份。" to "支援 JSON / CSV，匯入前建議先匯出備份。", "粘贴 JSON 或 CSV 数据" to "貼上 JSON 或 CSV 資料", "导入" to "匯入",
            "隐藏详情" to "隱藏詳情", "显示二维码" to "顯示 QR 碼", "复制号码" to "複製號碼", "删除号码？" to "刪除號碼？", "删除后不可恢复" to "刪除後不可復原",
            "如 AIS / Vodafone / 中国移动" to "如 AIS / Vodafone / 中國移動", "留空时会按号码和国家自动识别。" to "留空時會依號碼和國家自動識別。", "当前识别" to "目前識別", "当前选择" to "目前選擇", "推荐运营商" to "推薦電信商",
            "输入手机号码" to "輸入手機號碼", "如 1 RMB / 4.50 USD / 2GB" to "如 1 RMB / 4.50 USD / 2GB", "预付费 / 资费 / 套餐备注" to "預付費 / 資費 / 套餐備註", "在线 / 离线 / 漫游 / 无服务" to "線上 / 離線 / 漫遊 / 無服務",
            "输入 EID" to "輸入 EID", "服务器地址" to "伺服器地址", "未填写激活信息" to "未填寫啟用資訊", "可扫描/粘贴二维码内容，或从相册选择二维码图片" to "可掃描/貼上 QR 碼內容，或從相簿選擇 QR 碼圖片", "扫描二维码" to "掃描 QR 碼", "相册读取" to "相簿讀取", "激活信息已填写" to "啟用資訊已填寫",
            "未记录" to "未記錄", "填写二维码内容" to "填寫 QR 碼內容", "可粘贴 LPA、SM-DP+ 或激活码，保存后自动解析。" to "可貼上 LPA、SM-DP+ 或啟用碼，儲存後自動解析。", "LPA:1\$SM-DP+\$激活码" to "LPA:1\$SM-DP+\$啟用碼",
            "年" to "年", "月" to "月", "日" to "日", "今天" to "今天", "7天后" to "7天後", "30天后" to "30天後", "90天后" to "90天後",
            "云端地址未填写" to "雲端地址未填寫", "API Key 未填写" to "API Key 未填寫"
        ),
        "English" to mapOf(
            "流量接口" to "Traffic endpoint", "流量接口 URL" to "Traffic endpoint URL", "默认流量 KB" to "Default traffic KB",
            "下载测试接口" to "Download test endpoint", "目标流量" to "Target traffic", "例：100KB / 1MB / 50MB" to "Example: 100KB / 1MB / 50MB",
            "204 / 空响应接口不能真正消耗流量，建议使用 Cloudflare 或 Hetzner。" to "204 / empty-response endpoints do not consume real traffic. Use Cloudflare or Hetzner.",
            "开始刷流量" to "Start traffic test", "确认刷流量？" to "Confirm traffic test?", "将实际下载约" to "About to download", "确认后会真实消耗当前网络流量。" to "This will really consume current network data after confirmation.",
            "请求中…" to "Requesting…", "成功" to "Success", "实际读取" to "Read", "目标" to "Target", "耗时" to "Time", "秒" to "sec", "约" to "about", "失败" to "Failed",
            "选择刷流量号码" to "Select number for traffic test", "选择拨号号码" to "Select number to dial", "暂无号码，请先添加号码。" to "No numbers yet. Add one first.",
            "支持 JSON / CSV，导入前建议先导出备份。" to "Supports JSON / CSV. Export a backup before importing.", "粘贴 JSON 或 CSV 数据" to "Paste JSON or CSV data", "导入" to "Import",
            "隐藏详情" to "Hide details", "显示二维码" to "Show QR", "复制号码" to "Copy number", "删除号码？" to "Delete number?", "删除后不可恢复" to "This cannot be undone",
            "如 AIS / Vodafone / 中国移动" to "e.g. AIS / Vodafone / China Mobile", "留空时会按号码和国家自动识别。" to "Leave blank to auto-detect by number and country.", "当前识别" to "Detected", "当前选择" to "Selected", "推荐运营商" to "Suggested carriers",
            "输入手机号码" to "Enter phone number", "如 1 RMB / 4.50 USD / 2GB" to "e.g. 1 RMB / 4.50 USD / 2GB", "预付费 / 资费 / 套餐备注" to "Prepaid / tariff / plan note", "在线 / 离线 / 漫游 / 无服务" to "Online / Offline / Roaming / No service",
            "输入 EID" to "Enter EID", "服务器地址" to "Server address", "未填写激活信息" to "No activation info", "可扫描/粘贴二维码内容，或从相册选择二维码图片" to "Scan/paste QR content, or select a QR image from album", "扫描二维码" to "Scan QR", "相册读取" to "Read from album", "激活信息已填写" to "Activation info filled",
            "未记录" to "Not recorded", "填写二维码内容" to "Enter QR content", "可粘贴 LPA、SM-DP+ 或激活码，保存后自动解析。" to "Paste LPA, SM-DP+ or activation code; it will be parsed after saving.", "LPA:1\$SM-DP+\$激活码" to "LPA:1\$SM-DP+\$ActivationCode",
            "年" to "Year", "月" to "Month", "日" to "Day", "今天" to "Today", "7天后" to "In 7 days", "30天后" to "In 30 days", "90天后" to "In 90 days",
            "云端地址未填写" to "Cloud address is empty", "API Key 未填写" to "API Key is empty"
        ),
        "日本語" to mapOf(
            "流量接口" to "通信量テスト先", "流量接口 URL" to "通信量テストURL", "默认流量 KB" to "既定通信量 KB",
            "下载测试接口" to "ダウンロードテスト先", "目标流量" to "目標通信量", "例：100KB / 1MB / 50MB" to "例：100KB / 1MB / 50MB",
            "204 / 空响应接口不能真正消耗流量，建议使用 Cloudflare 或 Hetzner。" to "204/空応答のURLは通信量を消費しません。Cloudflare または Hetzner を推奨します。",
            "开始刷流量" to "通信量テスト開始", "确认刷流量？" to "通信量テストを確認？", "将实际下载约" to "実際に約", "确认后会真实消耗当前网络流量。" to "確認後、現在のネットワーク通信量を実際に消費します。",
            "请求中…" to "リクエスト中…", "成功" to "成功", "实际读取" to "読み取り", "目标" to "目標", "耗时" to "時間", "秒" to "秒", "约" to "約", "失败" to "失敗",
            "选择刷流量号码" to "通信量テスト番号を選択", "选择拨号号码" to "発信番号を選択", "暂无号码，请先添加号码。" to "番号がありません。先に追加してください。",
            "支持 JSON / CSV，导入前建议先导出备份。" to "JSON / CSV対応。インポート前にバックアップを推奨します。", "粘贴 JSON 或 CSV 数据" to "JSON または CSV を貼り付け", "导入" to "インポート",
            "隐藏详情" to "詳細を隠す", "显示二维码" to "QRを表示", "复制号码" to "番号をコピー", "删除号码？" to "番号を削除？", "删除后不可恢复" to "削除後は復元できません",
            "如 AIS / Vodafone / 中国移动" to "例：AIS / Vodafone / China Mobile", "留空时会按号码和国家自动识别。" to "空欄なら番号と国から自動識別します。", "当前识别" to "識別結果", "当前选择" to "選択中", "推荐运营商" to "推奨キャリア",
            "输入手机号码" to "電話番号を入力", "如 1 RMB / 4.50 USD / 2GB" to "例：1 RMB / 4.50 USD / 2GB", "预付费 / 资费 / 套餐备注" to "プリペイド / 料金 / メモ", "在线 / 离线 / 漫游 / 无服务" to "オンライン / オフライン / ローミング / 圏外",
            "输入 EID" to "EIDを入力", "服务器地址" to "サーバーアドレス", "未填写激活信息" to "有効化情報なし", "可扫描/粘贴二维码内容，或从相册选择二维码图片" to "QR内容をスキャン/貼り付け、またはアルバムから選択", "扫描二维码" to "QRスキャン", "相册读取" to "アルバムから読む", "激活信息已填写" to "有効化情報入力済み",
            "未记录" to "未記録", "填写二维码内容" to "QR内容を入力", "可粘贴 LPA、SM-DP+ 或激活码，保存后自动解析。" to "LPA、SM-DP+、有効化コードを貼り付けると保存後に解析します。", "LPA:1\$SM-DP+\$激活码" to "LPA:1\$SM-DP+\$ActivationCode",
            "年" to "年", "月" to "月", "日" to "日", "今天" to "今日", "7天后" to "7日後", "30天后" to "30日後", "90天后" to "90日後",
            "云端地址未填写" to "クラウドアドレス未入力", "API Key 未填写" to "API Key未入力"
        ),
        "阿拉伯语" to mapOf(
            "流量接口" to "واجهة البيانات", "流量接口 URL" to "رابط واجهة البيانات", "默认流量 KB" to "البيانات الافتراضية KB",
            "下载测试接口" to "واجهة اختبار التنزيل", "目标流量" to "حجم البيانات", "例：100KB / 1MB / 50MB" to "مثال: 100KB / 1MB / 50MB",
            "204 / 空响应接口不能真正消耗流量，建议使用 Cloudflare 或 Hetzner。" to "واجهات 204/الفارغة لا تستهلك بيانات فعلية. استخدم Cloudflare أو Hetzner.",
            "开始刷流量" to "بدء اختبار البيانات", "确认刷流量？" to "تأكيد اختبار البيانات؟", "将实际下载约" to "سيتم تنزيل حوالي", "确认后会真实消耗当前网络流量。" to "بعد التأكيد سيستهلك بيانات الشبكة فعليًا.",
            "请求中…" to "جارٍ الطلب…", "成功" to "نجاح", "实际读取" to "تمت القراءة", "目标" to "الهدف", "耗时" to "الوقت", "秒" to "ث", "约" to "حوالي", "失败" to "فشل",
            "选择刷流量号码" to "اختر رقم اختبار البيانات", "选择拨号号码" to "اختر رقم الاتصال", "暂无号码，请先添加号码。" to "لا توجد أرقام، أضف رقمًا أولاً.",
            "支持 JSON / CSV，导入前建议先导出备份。" to "يدعم JSON / CSV. يُفضل تصدير نسخة احتياطية قبل الاستيراد.", "粘贴 JSON 或 CSV 数据" to "الصق بيانات JSON أو CSV", "导入" to "استيراد",
            "隐藏详情" to "إخفاء التفاصيل", "显示二维码" to "إظهار QR", "复制号码" to "نسخ الرقم", "删除号码？" to "حذف الرقم؟", "删除后不可恢复" to "لا يمكن التراجع بعد الحذف",
            "如 AIS / Vodafone / 中国移动" to "مثل AIS / Vodafone / China Mobile", "留空时会按号码和国家自动识别。" to "اتركه فارغًا للتعرّف تلقائيًا حسب الرقم والدولة.", "当前识别" to "المكتشف", "当前选择" to "المحدد", "推荐运营商" to "مشغلون مقترحون",
            "输入手机号码" to "أدخل رقم الهاتف", "如 1 RMB / 4.50 USD / 2GB" to "مثل 1 RMB / 4.50 USD / 2GB", "预付费 / 资费 / 套餐备注" to "مسبق الدفع / التعرفة / ملاحظة", "在线 / 离线 / 漫游 / 无服务" to "متصل / غير متصل / تجوال / لا خدمة",
            "输入 EID" to "أدخل EID", "服务器地址" to "عنوان الخادم", "未填写激活信息" to "لا توجد معلومات تفعيل", "可扫描/粘贴二维码内容，或从相册选择二维码图片" to "امسح/الصق محتوى QR أو اختر صورة من الألبوم", "扫描二维码" to "مسح QR", "相册读取" to "قراءة من الألبوم", "激活信息已填写" to "تم إدخال معلومات التفعيل",
            "未记录" to "غير مسجل", "填写二维码内容" to "أدخل محتوى QR", "可粘贴 LPA、SM-DP+ 或激活码，保存后自动解析。" to "يمكن لصق LPA أو SM-DP+ أو رمز التفعيل وسيتم تحليله بعد الحفظ.", "LPA:1\$SM-DP+\$激活码" to "LPA:1\$SM-DP+\$ActivationCode",
            "年" to "السنة", "月" to "الشهر", "日" to "اليوم", "今天" to "اليوم", "7天后" to "بعد 7 أيام", "30天后" to "بعد 30 يومًا", "90天后" to "بعد 90 يومًا",
            "云端地址未填写" to "عنوان السحابة فارغ", "API Key 未填写" to "API Key فارغ"
        )
    )
    supplement[lang]?.get(key)?.let { return it }
    val zhHant = mapOf(
        "号码" to "號碼", "工具" to "工具", "设置" to "設定", "完成" to "完成", "取消" to "取消", "保存" to "儲存", "确认" to "確認", "确认延长" to "確認延長", "删除" to "刪除", "编辑" to "編輯", "保号" to "保號", "刷流量" to "刷流量", "搜索运营商、国家或号码" to "搜尋電信商、國家或號碼", "到期时间（远到近）" to "到期時間（遠到近）", "到期时间（近到远）" to "到期時間（近到遠）", "暂无号码" to "暫無號碼", "点击右下角添加号码" to "點擊右下角新增號碼", "工具" to "工具", "常用工具" to "常用工具", "拨号测试" to "撥號測試", "导出 JSON" to "匯出 JSON", "导出 CSV" to "匯出 CSV", "导入数据" to "匯入資料", "外观" to "外觀", "深色模式" to "深色模式", "更改背景图片" to "更改背景圖片", "清除" to "清除", "提醒设置" to "提醒設定", "开启到期提醒" to "開啟到期提醒", "语言 / Language" to "語言 / Language", "Telegram 通知" to "Telegram 通知", "关于" to "關於", "新增 eSIM" to "新增 eSIM", "编辑 eSIM" to "編輯 eSIM", "运营商与国家" to "電信商與國家", "国家/地区" to "國家/地區", "运营商名称" to "電信商名稱", "号码与套餐" to "號碼與套餐", "手机号码" to "手機號碼", "套餐余额" to "套餐餘額", "套餐备注" to "套餐備註", "信号状态" to "訊號狀態", "日期与周期" to "日期與週期", "开始日期" to "開始日期", "到期日期" to "到期日期", "套餐周期" to "套餐週期", "长期号码" to "長期號碼", "eSIM 激活信息" to "eSIM 啟用資訊", "编辑 EID" to "編輯 EID", "激活码" to "啟用碼", "记录信息" to "記錄資訊", "创建时间" to "建立時間", "激活时间" to "啟用時間", "选择国家区号" to "選擇國家區號", "国家区号库" to "國家區號庫", "全部国家 / 地区" to "全部國家 / 地區", "复制" to "複製", "导出文件" to "匯出檔案", "关闭" to "關閉", "好" to "好")
    val en = mapOf(
        "号码" to "Numbers", "工具" to "Tools", "设置" to "Settings", "完成" to "Done", "取消" to "Cancel", "保存" to "Save", "确认" to "Confirm", "确认延长" to "Extend", "删除" to "Delete", "编辑" to "Edit", "保号" to "Renew", "刷流量" to "Traffic", "搜索运营商、国家或号码" to "Search carrier, country or number", "到期时间（远到近）" to "Expiry date (far to near)", "到期时间（近到远）" to "Expiry date (near to far)", "暂无号码" to "No numbers", "点击右下角添加号码" to "Tap + to add a number", "常用工具" to "Tools", "选择一个号码执行真实下载流量测试" to "Pick a number and run a real download traffic test", "拨号测试" to "Dial test", "选择号码并打开系统拨号器" to "Pick a number and open system dialer", "导出 JSON" to "Export JSON", "生成完整 JSON 备份文本" to "Generate full JSON backup text", "导出 CSV" to "Export CSV", "生成 CSV 表格文本" to "Generate CSV table text", "导入数据" to "Import data", "粘贴 JSON 或 CSV 恢复号码列表" to "Paste JSON or CSV to restore records", "外观" to "Appearance", "深色模式" to "Dark mode", "更改背景图片" to "Change background", "清除" to "Clear", "提醒设置" to "Reminder settings", "开启到期提醒" to "Enable expiry reminders", "语言 / Language" to "Language", "Telegram 通知" to "Telegram notifications", "关于" to "About", "新增 eSIM" to "Add eSIM", "编辑 eSIM" to "Edit eSIM", "运营商与国家" to "Carrier & country", "国家/地区" to "Country/Region", "运营商名称" to "Carrier name", "号码与套餐" to "Number & plan", "手机号码" to "Phone number", "套餐余额" to "Plan balance", "套餐备注" to "Plan note", "信号状态" to "Signal status", "日期与周期" to "Dates & cycle", "开始日期" to "Start date", "到期日期" to "Expiry date", "套餐周期" to "Plan cycle", "长期号码" to "Long-term number", "eSIM 激活信息" to "eSIM activation info", "编辑 EID" to "Edit EID", "激活码" to "Activation code", "记录信息" to "Record info", "创建时间" to "Created at", "激活时间" to "Activated at", "选择国家区号" to "Select country code", "搜索国家 / 区号 / ISO" to "Search country / code / ISO", "国家区号库" to "Country code library", "全部国家 / 地区" to "All countries / regions", "当前语言：" to "Current language: ", "已启用 RTL 右到左布局" to "RTL right-to-left layout enabled", "支持实时切换，主要页面会立即刷新。" to "Language switches live on main pages.", "复制" to "Copy", "导出文件" to "Export file", "关闭" to "Close", "好" to "OK")
    val ja = mapOf(
        "号码" to "番号", "工具" to "ツール", "设置" to "設定", "完成" to "完了", "取消" to "キャンセル", "保存" to "保存", "确认" to "確認", "确认延长" to "延長", "删除" to "削除", "编辑" to "編集", "保号" to "維持", "刷流量" to "通信量", "搜索运营商、国家或号码" to "キャリア・国・番号を検索", "到期时间（远到近）" to "期限（遠い順）", "到期时间（近到远）" to "期限（近い順）", "暂无号码" to "番号なし", "点击右下角添加号码" to "右下の＋で追加", "常用工具" to "ツール", "拨号测试" to "発信テスト", "导出 JSON" to "JSON出力", "导出 CSV" to "CSV出力", "导入数据" to "データ取込", "外观" to "外観", "深色模式" to "ダークモード", "更改背景图片" to "背景を変更", "清除" to "クリア", "提醒设置" to "通知設定", "开启到期提醒" to "期限通知を有効化", "语言 / Language" to "言語 / Language", "Telegram 通知" to "Telegram通知", "关于" to "情報", "新增 eSIM" to "eSIM追加", "编辑 eSIM" to "eSIM編集", "运营商与国家" to "キャリアと国", "国家/地区" to "国/地域", "运营商名称" to "キャリア名", "号码与套餐" to "番号とプラン", "手机号码" to "電話番号", "套餐余额" to "残高", "套餐备注" to "プランメモ", "信号状态" to "信号状態", "日期与周期" to "日付と周期", "开始日期" to "開始日", "到期日期" to "期限日", "套餐周期" to "周期", "长期号码" to "長期番号", "eSIM 激活信息" to "eSIM有効化情報", "编辑 EID" to "EID編集", "激活码" to "アクティベーションコード", "记录信息" to "記録情報", "创建时间" to "作成日時", "激活时间" to "有効化日時", "选择国家区号" to "国番号を選択", "国家区号库" to "国番号ライブラリ", "全部国家 / 地区" to "すべての国/地域", "复制" to "コピー", "导出文件" to "ファイル出力", "关闭" to "閉じる", "好" to "OK")
    val ar = mapOf(
        "号码" to "الأرقام", "工具" to "الأدوات", "设置" to "الإعدادات", "完成" to "تم", "取消" to "إلغاء", "保存" to "حفظ", "确认" to "تأكيد", "确认延长" to "تمديد", "删除" to "حذف", "编辑" to "تعديل", "保号" to "تجديد", "刷流量" to "بيانات", "搜索运营商、国家或号码" to "ابحث عن المشغل أو الدولة أو الرقم", "到期时间（远到近）" to "انتهاء الصلاحية (الأبعد أولاً)", "到期时间（近到远）" to "انتهاء الصلاحية (الأقرب أولاً)", "暂无号码" to "لا توجد أرقام", "点击右下角添加号码" to "اضغط + لإضافة رقم", "常用工具" to "الأدوات", "拨号测试" to "اختبار الاتصال", "导出 JSON" to "تصدير JSON", "导出 CSV" to "تصدير CSV", "导入数据" to "استيراد البيانات", "外观" to "المظهر", "深色模式" to "الوضع الداكن", "更改背景图片" to "تغيير الخلفية", "清除" to "مسح", "提醒设置" to "إعدادات التذكير", "开启到期提醒" to "تفعيل تذكير الانتهاء", "语言 / Language" to "اللغة / Language", "Telegram 通知" to "إشعارات Telegram", "关于" to "حول", "新增 eSIM" to "إضافة eSIM", "编辑 eSIM" to "تعديل eSIM", "运营商与国家" to "المشغل والدولة", "国家/地区" to "الدولة/المنطقة", "运营商名称" to "اسم المشغل", "号码与套餐" to "الرقم والباقه", "手机号码" to "رقم الهاتف", "套餐余额" to "الرصيد", "套餐备注" to "ملاحظة الباقة", "信号状态" to "حالة الإشارة", "日期与周期" to "التاريخ والدورة", "开始日期" to "تاريخ البدء", "到期日期" to "تاريخ الانتهاء", "套餐周期" to "دورة الباقة", "长期号码" to "رقم طويل الأمد", "eSIM 激活信息" to "معلومات تفعيل eSIM", "编辑 EID" to "تعديل EID", "激活码" to "رمز التفعيل", "记录信息" to "معلومات السجل", "创建时间" to "تاريخ الإنشاء", "激活时间" to "تاريخ التفعيل", "选择国家区号" to "اختر رمز الدولة", "国家区号库" to "مكتبة رموز الدول", "全部国家 / 地区" to "كل الدول / المناطق", "复制" to "نسخ", "导出文件" to "تصدير ملف", "关闭" to "إغلاق", "好" to "حسنًا")
    return when(lang){"繁体中文"->zhHant[key];"English"->en[key];"日本語"->ja[key];"阿拉伯语"->ar[key];else->null} ?: key
}

fun dayText(lang:String, n:Long):String = when(lang){"English"->"$n days";"日本語"->"${n}日";"阿拉伯语"->"$n أيام";else->"${n}天"}
fun laterText(lang:String, n:Int):String = if(n==0) tr(lang,"今天") else when(lang){"English"->"$n days later";"日本語"->"${n}日後";"阿拉伯语"->"بعد $n أيام";else->"${n}天后"}
fun expireText(lang:String, days:Long?):String = when { days==null -> tr(lang,"未知"); days<0 -> tr(lang,"已过期") + when(lang){"English"->" ${-days} days";"日本語"->" ${-days}日";"阿拉伯语"->" ${-days} أيام";else->"${-days}天"}; else -> when(lang){"English"->"${days} days left";"日本語"->"残り${days}日";"阿拉伯语"->"متبقي $days أيام";else->"还有${days}天"} }
fun cycleText(lang:String, d:Int):String = if(d==365) tr(lang,"1年") else when(lang){"English"->"$d days";"日本語"->"${d}日";"阿拉伯语"->"$d أيام";else->"${d}天"}

